name: "units-test"
on:
  pull_request_target:
    branches:
      - master

jobs:
  PR-changed-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check Changed Files
        id: changed
        uses: citrix-workspace/g11n-PR-changed-files@master
        with:
          paths: .*i18n/.*\.json
      - name: Slack Notification
        if: steps.changed.outputs.matched == 'true'
        uses: archive/github-actions-slack@master        
        with:          
          slack-bot-user-oauth-access-token: ${{ secrets.SLACKBOT_TOKEN }}        
          slack-channel: gs-pipeline-notification
          slack-text: example--test-test
