name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: G11n Analysis
        uses: ./
        with:
          access-token: ${{ secrets.REVIEWTOKEN }}
          skip: 'bin/ lib/'
