name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: G11n Analysis
        uses: ./
        with:
          repoToken: ${{secrets.GITHUB_TOKEN}}
          skip: 'bin/ lib/'
